# RabbitMQ Configuration File
listeners.tcp.default = 49153

loopback_users.guest = false

heartbeat = 1000

## Logging
log.console = true
log.console.level = error
log.file.level = warning

## Management Plugin
management.load_definitions = /etc/rabbitmq/definitions.json
management.tcp.port = 49154

## Web STOMP Plugin
web_stomp.port = 49155

## MQTT Plugin
mqtt.proxy_protocol = true